version: '3.7'
services:
  db:
    image: "postgres"
    ports:
      - "5472:5432"
    env_file:
      - .env.postgres # configure postgres
    volumes:
      - beginning-prisma-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - beginning-prisma
volumes:
  beginning-prisma-data:
networks:
  beginning-prisma:
